checks:
  php: true

build:
  image: default-bionic
  environment:
        php: 8.1.2
  nodes:
    analysis:
      tests:
        override: [php-scrutinizer-run]
      cache:
        directories:
          - vendor/
filter:
  paths: ["src/*", "tests/*"]

tools:
  external_code_coverage: true
