checks:
  php: true

build:
  nodes:
    analysis:
      tests:
        override: [php-scrutinizer-run]
      cache:
        directories:
          - vendor/
filter:
  paths: ["src/*", "tests/*"]

tools:
  external_code_coverage: true
